version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: online_cinema_db
    environment:
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: cinema_password
      POSTGRES_DB: cinema_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: