"""remove unique constraint from order user_id

Revision ID: 87e6858781a4
Revises: 9c464d1308eb
Create Date: 2026-04-04 20:41:11.323931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e6858781a4'
down_revision: Union[str, Sequence[str], None] = '9c464d1308eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_user_id_key'), 'orders', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('orders_user_id_key'), 'orders', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
